omg:
  hostname: localhost

server:
  port: 8001

spring:
  application:
    name: payment-service-cloud
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
    url: jdbc:mysql://${omg.hostname}:3306/springcloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
mybatis-plus:
  type-aliases-package: top.omgdo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
